### ISSUE TITLE
Migrate to Apollo Client 3

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/create#35]

**Comment by schmidsi** [comment]
@Mikearaya Did you already start working on this?

**Comment by Mikearaya** [comment]
@schmidsi no I didn't look into the issue of this repo. But now I'll definitely get to it.

**Comment by Mikearaya** [comment]
Also I have thought about upgrading to apollo 3 but then I decided not to do it thinking it might be unnecessary since we only wanted to present the engine functionalities with bare minimum tools.

**Comment by schmidsi** [comment]
Yes: Bare minimum tools. But not outdated ones ;)

Therefore: Up to date, bare minimum tools. -> We need to upgrade to Apollo 3.

**Comment by Mikearaya** [comment]
this can be closed now.
