### ISSUE TITLE
npm run install-all fails

### ISSUE THREAD

**Issue by mhrsntrk** [unchainedshop/create#39]
Hello there,

I would like to try a fresh copy of unchained but it keeps failing when I try to npm run install-all. You can find terminal output and log files below.

npm run install-all

@unchainedshop/create@0.0.7 install-all
npm install && run-p --print-label install:*

added 64 packages, and audited 64 packages in 2s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[install:engine    ]
[install:engine    ] > @unchainedshop/create@0.0.7 install:engine
[install:engine    ] > cd engine && npm install
[install:engine    ]
[install:storefront]
[install:storefront] > @unchainedshop/create@0.0.7 install:storefront
[install:storefront] > cd storefront && npm install
[install:storefront]
[install:engine    ] npm ERR! Cannot read property 'matches' of undefined
[install:engine    ]
[install:engine    ] npm ERR! A complete log of this run can be found in:
[install:engine    ] npm ERR!     /Users/mahirsenturk/.npm/_logs/2020-11-19T07_43_33_442Z-debug.log
[install:engine    ] npm ERR! code 1
[install:engine    ] npm ERR! path /Users/mahirsenturk/Developer/your-awesome-ecommerce-project
[install:engine    ] npm ERR! command failed
[install:engine    ] npm ERR! command sh -c cd engine && npm install
[install:engine    ]
[install:engine    ] npm ERR! A complete log of this run can be found in:
[install:engine    ] npm ERR!     /Users/mahirsenturk/.npm/_logs/2020-11-19T07_43_33_545Z-debug.log
ERROR: "install:engine" exited with 1.
npm ERR! code 1
npm ERR! path /Users/mahirsenturk/Developer/your-awesome-ecommerce-project
npm ERR! command failed
npm ERR! command sh -c npm install && run-p --print-label install:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mahirsenturk/.npm/_logs/2020-11-19T07_43_33_716Z-debug.log

**Log Files:**

[2020-11-19T07_43_33_716Z-debug.log](https://github.com/unchainedshop/create/files/5565169/2020-11-19T07_43_33_716Z-debug.log)

[2020-11-19T07_43_33_442Z-debug.log](https://github.com/unchainedshop/create/files/5565164/2020-11-19T07_43_33_442Z-debug.log)

[2020-11-19T07_43_33_545Z-debug.log](https://github.com/unchainedshop/create/files/5565165/2020-11-19T07_43_33_545Z-debug.log)

**Comment by pozylon** [comment]
Thanks for reporting and detailed logs, we just received another very a similar feedback and we will improve the create app and the getting started parts of the website sooner than later

**Comment by schmidsi** [comment]
Hi @mhrsntrk, thanks for the report. Weird, this works perfectly on my computer. Do you have meteor installed? Can you run the installation of the modules manually? I.e. `cd engine && npm install`. What OS do you use?

One thing I noticed is your npm version 7. I use 6.14.6.

**Comment by Mikearaya** [comment]
I think we can close this as the issue is not there and can't be reproduced

**Comment by schmidsi** [comment]
@mhrsntrk Feel free to reopen this if the issue is still around.
