### ISSUE TITLE
Storefront cant be built. Exits with error

### ISSUE THREAD

**Issue by nabbl** [unchainedshop/create#50]
![image](https://user-images.githubusercontent.com/4679299/109150702-83b6d180-7769-11eb-8083-d1122978cfc6.png)

**Comment by Mikearaya** [comment]
@nabbl thank you for reporting this issue. can you please tell us the environment you are using to run unchained and the steps to reproduce this error? so we will get back to you ASAP.
Thanks

**Comment by Mikearaya** [comment]
Hi @nabbl this issue has is resolved so I'll close this for now. feel free to open this if you still see this issue.
