### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/create#53]
3-level category-structure:

- [x] N Root assortments in Menu, a mega dropdown will show secondary and ternary sub-categories (see publicare.ch)
- [x] Every category page has a title, subtitle, description and a cover image (needs unchained extension https://github.com/unchainedshop/unchained/issues/357), a breadcrumb, a list of products and a list of sub-categories (for ex. https://publicare.ch/de/shop/ergnzende-produkte-19)
- [x] Show a breadcrumb on every category page
- [x] Product lists just show thumbnail and title of articles in that category
- [x] No sorting or filtering required for the moment

**Comment by Mikearaya** [comment]
are all categories going to be three-tier or can they only have one tier?
