### ISSUE TITLE
Findings

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/create#69]
- [x] Menu on Desktop and Tablet does not behave the way it should (UX)
- [x] "In Cart" not translated
- [x] "Termin reservieren" is specific for Dynoptic, remove button from create, re-add to dynoptic fork
- [x] `$Unternehmen $Optional` & i_have_read_term in Checkout (Bestellung ohne Konto) 
- [x] No effect if I click on "Save" during edit of delivery address when going with a new user (country dropdown appears the first time and unstyled, it seems like country is a required field but it's not communicated)
- [x] Thank you page: date not formatted based on browser (Intl) and wrong:  an dem Sie die Bestellung aufgegeben haben, ist: 1/5/2021 -> should be  an dem Sie die Bestellung aufgegeben haben, ist: 1.6.2021
- [x] Whole "account" page looks like piece of shit and form does not work http://localhost:3000/account :) 
- [x] On "http://localhost:3000/account/change-password" it says "Passwort zurücksetzen / Reset Password" where as it should say "Passwort ändern / Set new Password", error if current password is wrong is not handled
- [x] "Continue shopping" on cart does redirect to the assortments index page, is that really nice that way?
- [x] We should show that Datatrans checkout is working fine in the demo and also provide that as a payment option (I put Datatrans credentials for sandbox into Team in 1Password so you can try to configure it localhost and make it work @Mikearaya)

**Comment by pozylon** [comment]
@Mikearaya @fliptation Please test the website front-to-back there are many small issues we can fix now before forking

**Comment by Mikearaya** [comment]
on it, and i totally agree with your account page remark.

**Comment by Mikearaya** [comment]
where would be the best redirect page for the continue page?. i think product categories is the right place.

**Comment by pozylon** [comment]
Maybe back to the parent assortment page of the product instead

**Comment by pozylon** [comment]
I select sunglasses then add to cart then continue: chances high i want to add more sunglasses to compare them later
