### ISSUE TITLE
Switching between delivery address and invoice address is slow

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/create#79]
1. Switching has a lag, consider using https://www.apollographql.com/docs/react/performance/optimistic-ui/
2. Delivery address and billing address are not always set correctly after checkout, this is the requirement:

- Billing address on order is always required and the delivery plugin will use the billing address when there is no delivery address set. -> Only set the delivery address additionally when these addresses differ from each other

**Comment by Mikearaya** [comment]
@pozylon can you describe a scenario where the inconsistency occurs?

**Comment by pozylon** [comment]
If you go to checkout "logged in" and directly checkout by wire transfer neither billing nor delivery address is set

result: https://dynoptic-template.unchained.wtf/orders/view/?_id=5jZGjuiyE4jNZn9zo

**Comment by pozylon** [comment]
What if you set the "billing address form" open at the start so the user has to "save" the billing address. At the same time I'd disable the payment method and payment button stuff as long as the edit form of the delivery or billing address is open.

**Comment by Mikearaya** [comment]
that is a good solution and after trying alternatives. I think it's will even more convenient if we remove the payment options if the delivery address is not set. but if set will be used for the billing address.
I've already implemented the straight path just need to identify the edge cases.

**Comment by Mikearaya** [comment]
Though optimized mutation slightly improved the speed there is still some lag. can you please check if you still can see the inconsistency between addresses?. turns out it was a simple cache problem with user query

**Comment by Mikearaya** [comment]
@pozylon
