### ISSUE TITLE
Newest version on npm seems to be ahead of master?

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/create#91]

**Comment by Mikearaya** [comment]
@pozylon no storefront is  https://github.com/unchainedshop/storefront which is not using gweiAmount. where did you see its used?

**Comment by pozylon** [comment]
Oh, yeah, you're right, maybe localhost:3000 was cached in some way...

but still on master it says "minimal" at one point but that doesn't exist anymore?

**Comment by pozylon** [comment]
https://github.com/unchainedshop/create/search?q=kitchensink @Mikearaya

**Comment by pozylon** [comment]
but it clearly checks out kitchensink :S

**Comment by Mikearaya** [comment]
@pozylon npm is using `main` branch  :zany_face:  I've rebased `master` now
